### ISSUE TITLE
Pending & Tx State Meta ticket

### ISSUE THREAD

**Issue by twblack88** [shapeshift/web#6403]
### Overview

Tx's history has been improving but as we add new features revisiting the display, polling, and filtering of Tx types and statuses is a good idea. 

user story: as a user when i hit confirm on any Tx type i expect it to show in my history.
as a user who left the page or navigated away when i sent a tx i want to be able to find the tx i sent and get it's status.

- [ ] change tx history to modals. so when you click they are both mobile friendly and have more information to show.
- [ ] add a pending row to tx history
- [ ] tool tips for history page (timestamp, status)

### References and additional details

 We had one spike and will likely need another to flesh out additional tickets. 

First implementation takeaways/summary: 
Add asset row without any details. the asset that you're sending, render in a `pending` state. if you click nothing happens. it doesn't expand. more intelligently update the statuses. We can see all the delays in the Daemon anyways so we can give some progress expected. we do that in modals for swaps so why not tx history. initiating a tx we have, add the extra data to capture a memo or pending status from other chains, grab the hash based on what data we do know and what we're waiting for. then when the other side completes we upsert and update the tx rows. 

**tx types to check:**
swap 
savers deposit/withdraw
LP deposit/withdraw
lending deposit/withdraw

### Acceptance Criteria

managing this though is a pain since some are ephemeral and others are complete. So handlers for the ephemeral is critical.

**Comment by twblack88** [comment]
Perhaps a quick thing to do is: We should combine pending, confirmed and failed txs. 99% of the time I click TX drawer it's to view a completed TX, and the other 1% I want to see a failed or pending one in the same list as the rest.

**Comment by twblack88** [comment]
clsing in favor of notification center.
